export const WORKFLOW_RUNTIME = Symbol("WORKFLOW_RUNTIME");
export const WORKFLOW_INSTANCE_STORE = Symbol("WORKFLOW_INSTANCE_STORE");
export const WORKFLOW_HISTORY_STORE = Symbol("WORKFLOW_HISTORY_STORE");
export const WORKFLOW_COMMAND_REGISTRY = Symbol("WORKFLOW_COMMAND_REGISTRY");
export const WORKFLOW_DEFINITION_REGISTRY = Symbol("WORKFLOW_DEFINITION_REGISTRY");
export const WORKFLOW_TRANSACTION_RUNNER = Symbol("WORKFLOW_TRANSACTION_RUNNER");
export const WORKFLOW_CLOCK = Symbol("WORKFLOW_CLOCK");
